### ISSUE TITLE
Add a final buildsystem

### ISSUE THREAD

**Issue by albfan** [ReneNyffenegger/gcc-create-library#3]
Why not end this example using meson or autotools to show how you can do all these steps using a buildsystem? No one is expected to do all this by hand, and you will lack lot of know-how it you do this way.

https://mesonbuild.com/IndepthTutorial.html

**Comment by ReneNyffenegger** [comment]
You're right. This was/is long on my bucket list. You already did meson. When I find time, I will tackle autotools - but don't expect it too soon.
